### ISSUE TITLE
Performance Issues

### ISSUE THREAD

**Issue by ansarizafar** [rknell/vmiso#1]
> VMISO provides super simple state management at the potential expense of some performance.

This library looks super simple. What are the potential performance issues?

**Comment by rknell** [comment]
It is really simple. 

It was made while getting my head around streams because I was having trouble with scoped model becoming messy (always having to have two widgets to perform one task), I didn't like redux because it had too much boilerplate in react native, and MobX has proven to be a moving target in RN as well, so I didn't want to commit to something so complex again.

We have used it now on a number of projects and never had any issues regarding performance, but the big thing to watch out for is that its not very targeted in issuing a UI redraw - ie, if your ViewModel is large, and you are doing frequent `notify()` calls for only updating a small part of the model, you might be better off splitting that off to its own stream (or even just make another viewmodel to subscribe to) - Basically it sends more than the absolutely minimal amount of data, but if it proves to be a bottleneck it should be pretty easy to refactor down the line too.

Otherwise it uses a well established mechanism within flutter (streams), uses Rx to seed to the stream, and its all pretty straightforward. I highly recommend reading the code if you can understand it - its something you could easily implement yourself within an hour, but its proven to elegantly solve the problem so I made it available.

I wasn't sure anybody would find it, so if there is something else you would like to know or more documentation made anywhere by all means hit me up.
